name: Snipecraft
version: 1.0
author: FerskiGames
main: me.FerskiGames.Snipecraft.Main
description: A plugin to turn the Spyglass into a sniper rifle.
api-version: 1.17

commands:
  sc:
    description: Snipecraft's main command.
    usage: /sc